name: Webhook Events

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"action":"${{ github.event_name }}","repository":"${{ github.repository }}","author":"${{ github.actor }}","branch":"${{ github.ref_name }}","timestamp":"${{ github.event.head_commit.timestamp }}"}' \
          $WEBHOOK_URL
